### ISSUE TITLE
Review November 16

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/vertnet_explore#1]
# To-do 

## From our in person meeting
- [x] README.md that lists the code in code directory example: [https://github.com/DiscoveryDNA/TFBS_presence](https://github.com/DiscoveryDNA/TFBS_presence).
- [ ] definitely make a note about the discrepancy between calling all the data: https://github.com/cabinetofcuriosity/vertnet_explore/blob/master/code/1_Obtaining_Vertnet_Data.ipynb
- [x] Contact someone at Vertnet, David Bloom, no response
- [x] Contact Michelle Koo about historical context of database.  
- [ ] Talk about the problem in discrepancy of returning data
- [ ] Deal with serving the data in notebook 2 somewhere else. 
- [x] Can you send me how to link to an interactive plot on plotly server.

## Notebook 1: 1_Obtaining_Vertnet_Data.ipynb

- [ ] Excellent introduction! Can you add some information why you were interested in this database?  
- [ ] It would be great to add a brief conclusion.

## Notebook 2: 2_Focusing_Vertnet_Data.ipynb
- [ ] I made notes in the notebook. They all start with "**Ciera**:" Please look over. 
- [ ] There is an error when I try to run the plotly plots. Never really worked with plotly, but do you know what this is about?
>PlotlyError: Because you didn't supply a 'file_id' in the call, we're assuming you're trying to snag a figure from a url. You supplied the url, '', we expected it to start with 'https://plot.ly'.
Run help on this function for more information.
- [ ] check to see if plotly graphs can be embedded into notebook

**Comment by iamciera** [comment]
- [ ] Look into possibility to work on the Discovery DNA project (Ciera) 
- [ ] Can you add the links to the interactive.
- [ ] Talk to Plotly (Ciera) about getting students unlimited access. 
- [ ] Talk to Rebecca to set up meeting about scaling the colors on continuous color plots.
